name: food-optimization-env
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3
 - pandas
 - requests
 - beautifulsoup4
 - lxml
 - matplotlib
 - jupyter
 - tqdm
# - glpk
 - selenium
 - coincbc
 - pip:
   - pulp